/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assassinscreedfratellanzadelleombre;

/**
 *
 * @author bianconi.yurinabil
 */
public class SchermataInizioGioco extends javax.swing.JPanel {

    /**
     * Creates new form SchermataInizioGioco
     */
    public SchermataInizioGioco() {
        initComponents();
        
        labelSfondoSchermataIniziale.getResource("/AssassinCreedFratellanzaDelleOmbre/immagini");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottoneLeggiStoria = new javax.swing.JButton();
        bottoneIniziaGioco1 = new javax.swing.JButton();
        bottoneContinuaGioco1 = new javax.swing.JButton();
        labelSfondoSchermataIniziale = new javax.swing.JLabel();

        setLayout(null);

        bottoneLeggiStoria.setBackground(new java.awt.Color(102, 0, 0));
        bottoneLeggiStoria.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        bottoneLeggiStoria.setForeground(new java.awt.Color(242, 242, 242));
        bottoneLeggiStoria.setText("LEGGI STORIA");
        add(bottoneLeggiStoria);
        bottoneLeggiStoria.setBounds(330, 430, 170, 40);

        bottoneIniziaGioco1.setBackground(new java.awt.Color(102, 0, 0));
        bottoneIniziaGioco1.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        bottoneIniziaGioco1.setForeground(new java.awt.Color(242, 242, 242));
        bottoneIniziaGioco1.setText("INIZIA GIOCO");
        add(bottoneIniziaGioco1);
        bottoneIniziaGioco1.setBounds(330, 330, 170, 40);

        bottoneContinuaGioco1.setBackground(new java.awt.Color(102, 0, 0));
        bottoneContinuaGioco1.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        bottoneContinuaGioco1.setForeground(new java.awt.Color(242, 242, 242));
        bottoneContinuaGioco1.setText("CONTINUA ");
        add(bottoneContinuaGioco1);
        bottoneContinuaGioco1.setBounds(330, 380, 170, 40);

        labelSfondoSchermataIniziale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassinscreedfratellanzadelleombre/sfondoInizioGioco.png"))); // NOI18N
        add(labelSfondoSchermataIniziale);
        labelSfondoSchermataIniziale.setBounds(0, -10, 820, 520);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneContinuaGioco1;
    private javax.swing.JButton bottoneIniziaGioco1;
    private javax.swing.JButton bottoneLeggiStoria;
    private javax.swing.JLabel labelSfondoSchermataIniziale;
    // End of variables declaration//GEN-END:variables
}
