/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assassinscreedfratellanzadelleombre;

/**
 *
 * @author bianconi.yurinabil
 */
public class SchermataInizioGioco extends javax.swing.JFrame {

    /**
     * Creates new form SchermataInizioGioco
     */
    private SchermataStoria sc1;
    public SchermataInizioGioco() {
        initComponents();
        sc1 = new SchermataStoria();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottoneLeggiStoria = new javax.swing.JButton();
        bottoneIniziaGioco = new javax.swing.JButton();
        bottoneContinuaGioco = new javax.swing.JButton();
        labelSfondoSchermataIniziale = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        bottoneLeggiStoria.setBackground(new java.awt.Color(102, 0, 0));
        bottoneLeggiStoria.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        bottoneLeggiStoria.setForeground(new java.awt.Color(242, 242, 242));
        bottoneLeggiStoria.setText("LEGGI STORIA");
        bottoneLeggiStoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneLeggiStoriaActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneLeggiStoria);
        bottoneLeggiStoria.setBounds(330, 430, 170, 40);

        bottoneIniziaGioco.setBackground(new java.awt.Color(102, 0, 0));
        bottoneIniziaGioco.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        bottoneIniziaGioco.setForeground(new java.awt.Color(242, 242, 242));
        bottoneIniziaGioco.setText("INIZIA GIOCO");
        bottoneIniziaGioco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneIniziaGiocoActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneIniziaGioco);
        bottoneIniziaGioco.setBounds(330, 330, 170, 40);

        bottoneContinuaGioco.setBackground(new java.awt.Color(102, 0, 0));
        bottoneContinuaGioco.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        bottoneContinuaGioco.setForeground(new java.awt.Color(242, 242, 242));
        bottoneContinuaGioco.setText("CONTINUA ");
        getContentPane().add(bottoneContinuaGioco);
        bottoneContinuaGioco.setBounds(330, 380, 170, 40);

        labelSfondoSchermataIniziale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassinscreedfratellanzadelleombre/sfondoInizioGioco.png"))); // NOI18N
        getContentPane().add(labelSfondoSchermataIniziale);
        labelSfondoSchermataIniziale.setBounds(0, -10, 820, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneIniziaGiocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneIniziaGiocoActionPerformed
        GameManager gm = new GameManager();
        
        SchermataSceltaPersonaggi sceltaP1 = new SchermataSceltaPersonaggi(gm);
        sceltaP1.setVisible(true);
        sceltaP1.setSize(818,540);
        this.dispose();
    }//GEN-LAST:event_bottoneIniziaGiocoActionPerformed

    private void bottoneLeggiStoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneLeggiStoriaActionPerformed

        sc1.setVisible(true);
        sc1.setSize(837,540);
        this.dispose();
        
    }//GEN-LAST:event_bottoneLeggiStoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneContinuaGioco;
    private javax.swing.JButton bottoneIniziaGioco;
    private javax.swing.JButton bottoneLeggiStoria;
    private javax.swing.JLabel labelSfondoSchermataIniziale;
    // End of variables declaration//GEN-END:variables
}
