/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assassinscreedfratellanzadelleombre;

/**
 *
 * @author bianconi.yurinabil
 */
public class SchermataInizioGioco extends javax.swing.JFrame {

    /**
     * Creates new form SchermataInizioGioco
     */
    private SchermataStoria sc1;
    
    public SchermataInizioGioco() {
        initComponents();
        sc1 = new SchermataStoria();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottoneContinuaGiocoSrz = new javax.swing.JButton();
        bottoneIniziaGioco = new javax.swing.JButton();
        bottoneLeggiStoria1 = new javax.swing.JButton();
        bottoneContinuaGiocoTxt = new javax.swing.JButton();
        labelSfondoSchermataIniziale = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        bottoneContinuaGiocoSrz.setBackground(new java.awt.Color(102, 0, 0));
        bottoneContinuaGiocoSrz.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        bottoneContinuaGiocoSrz.setForeground(new java.awt.Color(242, 242, 242));
        bottoneContinuaGiocoSrz.setText("CONTINUA SRZ");
        bottoneContinuaGiocoSrz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneContinuaGiocoSrz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneContinuaGiocoSrzActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneContinuaGiocoSrz);
        bottoneContinuaGiocoSrz.setBounds(330, 450, 170, 30);

        bottoneIniziaGioco.setBackground(new java.awt.Color(102, 0, 0));
        bottoneIniziaGioco.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        bottoneIniziaGioco.setForeground(new java.awt.Color(242, 242, 242));
        bottoneIniziaGioco.setText("INIZIA GIOCO");
        bottoneIniziaGioco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneIniziaGioco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneIniziaGiocoActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneIniziaGioco);
        bottoneIniziaGioco.setBounds(330, 330, 170, 30);

        bottoneLeggiStoria1.setBackground(new java.awt.Color(102, 0, 0));
        bottoneLeggiStoria1.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        bottoneLeggiStoria1.setForeground(new java.awt.Color(242, 242, 242));
        bottoneLeggiStoria1.setText("LEGGI STORIA");
        bottoneLeggiStoria1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneLeggiStoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneLeggiStoria1ActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneLeggiStoria1);
        bottoneLeggiStoria1.setBounds(330, 410, 170, 30);

        bottoneContinuaGiocoTxt.setBackground(new java.awt.Color(102, 0, 0));
        bottoneContinuaGiocoTxt.setFont(new java.awt.Font("Cinzel", 1, 18)); // NOI18N
        bottoneContinuaGiocoTxt.setForeground(new java.awt.Color(242, 242, 242));
        bottoneContinuaGiocoTxt.setText("CONTINUA TXT");
        bottoneContinuaGiocoTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneContinuaGiocoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneContinuaGiocoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneContinuaGiocoTxt);
        bottoneContinuaGiocoTxt.setBounds(330, 370, 170, 30);

        labelSfondoSchermataIniziale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassinscreedfratellanzadelleombre/sfondoInizioGioco.png"))); // NOI18N
        getContentPane().add(labelSfondoSchermataIniziale);
        labelSfondoSchermataIniziale.setBounds(0, -10, 820, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneIniziaGiocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneIniziaGiocoActionPerformed
        GameManager gm = new GameManager();
        
        SchermataSceltaPersonaggi sceltaP1 = new SchermataSceltaPersonaggi(gm);
        sceltaP1.setVisible(true);
        sceltaP1.setSize(818,540);
        this.dispose();
    }//GEN-LAST:event_bottoneIniziaGiocoActionPerformed

    private void bottoneContinuaGiocoSrzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneContinuaGiocoSrzActionPerformed
                
        GameManager gm = FileManager.caricaGiocoSerializzato();
        
        if (gm != null) {
            SchermataCombattimentoGioco scm1 = new SchermataCombattimentoGioco(gm);
            scm1.setVisible(true);
            scm1.setSize(837,540);
            this.dispose();
        }
        else {
            javax.swing.JOptionPane.showMessageDialog(null,"Nessun salvataggio trovato");
        }
        
        
    }//GEN-LAST:event_bottoneContinuaGiocoSrzActionPerformed

    private void bottoneContinuaGiocoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneContinuaGiocoTxtActionPerformed
        Object[] dati = FileManager.caricaGioco();
        
        if (dati != null) {
            GameManager gm = new GameManager();
            gm.caricaPartita(dati);
            SchermataCombattimentoGioco scm1 = new SchermataCombattimentoGioco(gm);
            scm1.setVisible(true);
            scm1.setSize(837,540);
            this.dispose();
            
        }
        else {
            javax.swing.JOptionPane.showMessageDialog(null, "nessun salvataggio trovato"); //idea presa da game over e vittoria
        }

    }//GEN-LAST:event_bottoneContinuaGiocoTxtActionPerformed

    private void bottoneLeggiStoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneLeggiStoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottoneLeggiStoria1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneContinuaGiocoSrz;
    private javax.swing.JButton bottoneContinuaGiocoTxt;
    private javax.swing.JButton bottoneIniziaGioco;
    private javax.swing.JButton bottoneLeggiStoria1;
    private javax.swing.JLabel labelSfondoSchermataIniziale;
    // End of variables declaration//GEN-END:variables
}
