/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assassinscreedfratellanzadelleombre;

/**
 *
 * @author bianconi.yurinabil
 */
public class SchermataCombattimentoGioco extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataCombattimentoGioco.class.getName());

    /**
     * Creates new form SchermataCombattimentoGioco
     */
    private GameManager gameManager;
    public SchermataCombattimentoGioco(GameManager gm1) {
        this.gameManager = gm1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bottoneCurati = new javax.swing.JButton();
        bottoneAttacca = new javax.swing.JButton();
        bottoneSpeciale = new javax.swing.JButton();
        bottoneNasconditi = new javax.swing.JButton();
        labelNomePlayer = new javax.swing.JLabel();
        labelVitaPlayer = new javax.swing.JLabel();
        labelEnergia = new javax.swing.JLabel();
        SfondoCombattimento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 370, 300, 110);

        bottoneCurati.setText("CURATI");
        getContentPane().add(bottoneCurati);
        bottoneCurati.setBounds(400, 200, 160, 40);

        bottoneAttacca.setText("ATTACCA");
        getContentPane().add(bottoneAttacca);
        bottoneAttacca.setBounds(230, 130, 160, 40);

        bottoneSpeciale.setText("MOSSA SPECIALE");
        getContentPane().add(bottoneSpeciale);
        bottoneSpeciale.setBounds(230, 200, 160, 40);

        bottoneNasconditi.setText("NASCONDITI");
        getContentPane().add(bottoneNasconditi);
        bottoneNasconditi.setBounds(400, 130, 160, 40);

        labelNomePlayer.setText("jLabel2");
        getContentPane().add(labelNomePlayer);
        labelNomePlayer.setBounds(30, 40, 180, 40);

        labelVitaPlayer.setText("jLabel2");
        getContentPane().add(labelVitaPlayer);
        labelVitaPlayer.setBounds(30, 410, 180, 30);

        labelEnergia.setText("jLabel1");
        getContentPane().add(labelEnergia);
        labelEnergia.setBounds(30, 450, 180, 30);

        SfondoCombattimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassinscreedfratellanzadelleombre/SfondoCombattimento.png"))); // NOI18N
        getContentPane().add(SfondoCombattimento);
        SfondoCombattimento.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SfondoCombattimento;
    private javax.swing.JButton bottoneAttacca;
    private javax.swing.JButton bottoneCurati;
    private javax.swing.JButton bottoneNasconditi;
    private javax.swing.JButton bottoneSpeciale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEnergia;
    private javax.swing.JLabel labelNomePlayer;
    private javax.swing.JLabel labelVitaPlayer;
    // End of variables declaration//GEN-END:variables
}
