/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assassinscreedfratellanzadelleombre;

import static java.awt.GridBagConstraints.BOTH;

/**
 *
 * @author bianconi.yurinabil
 */
public class SchermataSceltaPersonaggi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataSceltaPersonaggi.class.getName());
    
    /**
     * Creates new form SchermataSceltaPersonaggi
     */
    private GameManager gameManager;

    public SchermataSceltaPersonaggi(GameManager gm1) {
        this.gameManager = gm1;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottoneSelezionaKassandra = new javax.swing.JButton();
        bottoneSelezionaShay = new javax.swing.JButton();
        bottoneSelezionaEzio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bottoneSelezionaKassandra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassinscreedfratellanzadelleombre/seleziona_bottone.png"))); // NOI18N
        bottoneSelezionaKassandra.setText("jButton1");
        bottoneSelezionaKassandra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneSelezionaKassandra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneSelezionaKassandraActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneSelezionaKassandra);
        bottoneSelezionaKassandra.setBounds(530, 410, 180, 40);

        bottoneSelezionaShay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassinscreedfratellanzadelleombre/seleziona_bottone.png"))); // NOI18N
        bottoneSelezionaShay.setText("jButton1");
        bottoneSelezionaShay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneSelezionaShay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneSelezionaShayActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneSelezionaShay);
        bottoneSelezionaShay.setBounds(80, 410, 180, 40);

        bottoneSelezionaEzio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassinscreedfratellanzadelleombre/seleziona_bottone.png"))); // NOI18N
        bottoneSelezionaEzio.setText("jButton1");
        bottoneSelezionaEzio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottoneSelezionaEzio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneSelezionaEzioActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneSelezionaEzio);
        bottoneSelezionaEzio.setBounds(310, 410, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassinscreedfratellanzadelleombre/sfondoSceltaPersonaggio.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneSelezionaKassandraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneSelezionaKassandraActionPerformed
        gameManager.selezionaPersonaggio("KASSANDRA");
        gameManager.generaNemico();
        SchermataCombattimentoGioco schermata = new SchermataCombattimentoGioco (gameManager);
        schermata.setVisible(true);
        schermata.setSize(818,540);
//        setExtendedState(javax.swing.JFrame.MAXIMIZED BOTH);
        this.dispose();
    }//GEN-LAST:event_bottoneSelezionaKassandraActionPerformed

    private void bottoneSelezionaShayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneSelezionaShayActionPerformed
        gameManager.selezionaPersonaggio("SHAY");
        gameManager.generaNemico();
        SchermataCombattimentoGioco schermata = new SchermataCombattimentoGioco (gameManager);
        schermata.setVisible(true);
        schermata.setSize(818,540);
        this.dispose();
    }//GEN-LAST:event_bottoneSelezionaShayActionPerformed

    private void bottoneSelezionaEzioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneSelezionaEzioActionPerformed
        gameManager.selezionaPersonaggio("EZIO");
        gameManager.generaNemico();
        SchermataCombattimentoGioco schermata = new SchermataCombattimentoGioco (gameManager);
        schermata.setVisible(true);
        schermata.setSize(818,540);
        this.dispose();
    }//GEN-LAST:event_bottoneSelezionaEzioActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneSelezionaEzio;
    private javax.swing.JButton bottoneSelezionaKassandra;
    private javax.swing.JButton bottoneSelezionaShay;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
