/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assassinscreedfratellanzadelleombre;

/**
 *
 * @author bianconi.yurinabil
 */
public class SchermataStoria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataStoria.class.getName());

    /**
     * Creates new form SchermataStoria
     */
    private SchermataInizioGioco sig1;
    public SchermataStoria() {
        initComponents();
       // sig1 = new SchermataInizioGioco();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottoneIndietroStoria = new javax.swing.JButton();
        schemataStoriaFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bottoneIndietroStoria.setBackground(new java.awt.Color(118, 100, 65));
        bottoneIndietroStoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bottoneIndietroStoria.setText("INDIETRO");
        bottoneIndietroStoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneIndietroStoriaActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneIndietroStoria);
        bottoneIndietroStoria.setBounds(10, 20, 140, 40);

        schemataStoriaFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassinscreedfratellanzadelleombre/schermataStoriaFoto.png"))); // NOI18N
        getContentPane().add(schemataStoriaFoto);
        schemataStoriaFoto.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneIndietroStoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneIndietroStoriaActionPerformed
        SchermataInizioGioco s1 = new SchermataInizioGioco();
        s1.setVisible(true);
        s1.setSize(837,540);
        this.dispose();
    }//GEN-LAST:event_bottoneIndietroStoriaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneIndietroStoria;
    private javax.swing.JLabel schemataStoriaFoto;
    // End of variables declaration//GEN-END:variables
}
