/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assassinscreedfratellanzadelleombre;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author bianconi.yurinabil
 */
public class SchermataCombattimentoGioco extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataCombattimentoGioco.class.getName());

    /**
     * Creates new form SchermataCombattimentoGioco
     */
    private GameManager gameManager;
    public SchermataCombattimentoGioco(GameManager gm1) {
        this.gameManager = gm1;
        initComponents();
        aggiornaSchermata();
        aggiornaImmagini();   
        java.net.URL test = getClass().getResource("/assassinscreedfratellanzadelleombre/immagini/ezio.png");

System.out.println(test);

    }
    
    private void aggiornaSchermata() {
        
        Personaggio p = gameManager.getGiocatore();
        Nemico n = gameManager.getNemico();
        
        labelNomePlayer.setText(p.getNome());
        labelVitaPlayer.setText("VITA: " + p.getVita());
        labelEnergia.setText("ENERGIA: " + p.getEnergia());
        labelNomeNemico.setText(n.getNome());
        labelVitaNemico.setText("VITA: " + n.getVita());
        barraVitaPlayer.setValue(p.getVita());
        barraVitaNemico.setValue(n.getVita());
    }
    
    private void aggiornaImmagini() {

    String nomePlayer = gameManager.getGiocatore().getNome();

    if (nomePlayer.contains("EZIO")){
        setImmagine(immaginePlayer, "/assassinscreedfratellanzadelleombre/immagini/ezio.png");
    }

    if (nomePlayer.contains("SHAY")){
        setImmagine(immaginePlayer, "/assassinscreedfratellanzadelleombre/immagini/shay.png");
    }

    if (nomePlayer.contains("KASSANDRA")){
        setImmagine(immaginePlayer, "/assassinscreedfratellanzadelleombre/immagini/kassandra.png");
    }

    String nomeNemico = gameManager.getNemico().getNome();

    if (nomeNemico.contains("Spia")){
        setImmagine(immagineNemico, "/assassinscreedfratellanzadelleombre/immagini/spia.png");
    }

    if (nomeNemico.contains("Guerriero")){
        setImmagine(immagineNemico, "/assassinscreedfratellanzadelleombre/immagini/guerriero.png");
    }

    if (nomeNemico.contains("Assassino")){
        setImmagine(immagineNemico, "/assassinscreedfratellanzadelleombre/immagini/assassino.png");
    }
}

    
private void setImmagine(JLabel label, String path){

    java.net.URL url = getClass().getResource(path);

    if(url == null){
        System.out.println("ERRORE: immagine non trovata -> " + path);
        return;
    }

    ImageIcon icon = new ImageIcon(url);
    Image img = icon.getImage();

    Image imgScaled = img.getScaledInstance(
        label.getWidth(),
        label.getHeight(),
        Image.SCALE_SMOOTH
    );

    label.setIcon(new ImageIcon(imgScaled));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottoneCurati = new javax.swing.JButton();
        bottoneAttacca = new javax.swing.JButton();
        bottoneSpeciale = new javax.swing.JButton();
        bottoneNasconditi = new javax.swing.JButton();
        labelVitaNemico = new javax.swing.JLabel();
        labelVitaPlayer = new javax.swing.JLabel();
        labelEnergia = new javax.swing.JLabel();
        labelNomePlayer = new javax.swing.JLabel();
        labelNomeNemico = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTestoCombattimento = new javax.swing.JTextArea();
        barraVitaNemico = new javax.swing.JProgressBar();
        barraVitaPlayer = new javax.swing.JProgressBar();
        immagineNemico = new javax.swing.JLabel();
        immaginePlayer = new javax.swing.JLabel();
        SfondoCombattimento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bottoneCurati.setText("CURATI");
        bottoneCurati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneCuratiActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneCurati);
        bottoneCurati.setBounds(400, 200, 160, 40);

        bottoneAttacca.setText("ATTACCA");
        bottoneAttacca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneAttaccaActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneAttacca);
        bottoneAttacca.setBounds(230, 130, 160, 40);

        bottoneSpeciale.setText("MOSSA SPECIALE");
        bottoneSpeciale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneSpecialeActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneSpeciale);
        bottoneSpeciale.setBounds(230, 200, 160, 40);

        bottoneNasconditi.setText("NASCONDITI");
        bottoneNasconditi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneNasconditiActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneNasconditi);
        bottoneNasconditi.setBounds(400, 130, 160, 40);

        labelVitaNemico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelVitaNemico.setForeground(new java.awt.Color(255, 255, 255));
        labelVitaNemico.setText("VITA:");
        getContentPane().add(labelVitaNemico);
        labelVitaNemico.setBounds(590, 410, 180, 30);

        labelVitaPlayer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelVitaPlayer.setForeground(new java.awt.Color(255, 255, 255));
        labelVitaPlayer.setText("VITA");
        getContentPane().add(labelVitaPlayer);
        labelVitaPlayer.setBounds(30, 410, 180, 30);

        labelEnergia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelEnergia.setForeground(new java.awt.Color(255, 255, 255));
        labelEnergia.setText("ENERGIA");
        getContentPane().add(labelEnergia);
        labelEnergia.setBounds(30, 450, 180, 30);

        labelNomePlayer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNomePlayer.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelNomePlayer);
        labelNomePlayer.setBounds(30, 40, 180, 40);

        labelNomeNemico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNomeNemico.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelNomeNemico);
        labelNomeNemico.setBounds(590, 40, 180, 40);

        areaTestoCombattimento.setColumns(20);
        areaTestoCombattimento.setRows(5);
        jScrollPane2.setViewportView(areaTestoCombattimento);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(280, 380, 234, 86);
        getContentPane().add(barraVitaNemico);
        barraVitaNemico.setBounds(590, 10, 180, 20);
        getContentPane().add(barraVitaPlayer);
        barraVitaPlayer.setBounds(30, 10, 180, 20);
        getContentPane().add(immagineNemico);
        immagineNemico.setBounds(600, 110, 160, 270);
        getContentPane().add(immaginePlayer);
        immaginePlayer.setBounds(40, 110, 160, 270);

        SfondoCombattimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassinscreedfratellanzadelleombre/SfondoCombattimento.png"))); // NOI18N
        getContentPane().add(SfondoCombattimento);
        SfondoCombattimento.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneAttaccaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneAttaccaActionPerformed
        gameManager.attaccoGiocatore();
        areaTestoCombattimento.setText("Hai attaccato il nemico!");
        aggiornaSchermata();
    }//GEN-LAST:event_bottoneAttaccaActionPerformed

    private void bottoneSpecialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneSpecialeActionPerformed
        gameManager.usaAbilita();
        areaTestoCombattimento.setText("Hai usato la tua abilita speciale!");
        aggiornaSchermata();
    }//GEN-LAST:event_bottoneSpecialeActionPerformed

    private void bottoneCuratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneCuratiActionPerformed
        if (gameManager.getGiocatore().curati()){
            areaTestoCombattimento.setText("Ti sei curato!");
        }
        else {
            areaTestoCombattimento.setText("Nessuna cura disponibile!");
        }
        aggiornaSchermata();
    }//GEN-LAST:event_bottoneCuratiActionPerformed

    private void bottoneNasconditiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneNasconditiActionPerformed
        areaTestoCombattimento.setText("Ti sei nascosto!");
    }//GEN-LAST:event_bottoneNasconditiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SfondoCombattimento;
    private javax.swing.JTextArea areaTestoCombattimento;
    private javax.swing.JProgressBar barraVitaNemico;
    private javax.swing.JProgressBar barraVitaPlayer;
    private javax.swing.JButton bottoneAttacca;
    private javax.swing.JButton bottoneCurati;
    private javax.swing.JButton bottoneNasconditi;
    private javax.swing.JButton bottoneSpeciale;
    private javax.swing.JLabel immagineNemico;
    private javax.swing.JLabel immaginePlayer;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelEnergia;
    private javax.swing.JLabel labelNomeNemico;
    private javax.swing.JLabel labelNomePlayer;
    private javax.swing.JLabel labelVitaNemico;
    private javax.swing.JLabel labelVitaPlayer;
    // End of variables declaration//GEN-END:variables
}
